server:
  port: 8080
  tomcat:
    relaxed-query-chars: '^'

spring:
  main:
    banner-mode: "off"
  application: fractional-computation-api

logging:
  level:
    root: INFO
    com.trbaxter.github.fractionalcomputationapi: DEBUG
    org.springframework: INFO