server:
  port: 8080

spring:
  main:
    banner-mode: off  # Removes Spring title banner when API starts
  application: fractional-calculus-computation-api

logging:
  level:
    root: INFO  # Only logs messages at INFO level and above (WARN, ERROR, FATAL)
    com.trbaxter.github.fractionalcomputationapi: DEBUG  # Logs DEBUG, INFO, WARN, ERROR, and FATAL messages
    org.springframework: INFO  # Only logs messages at INFO level and above (WARN, ERROR, FATAL)