spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  main:
    banner-mode: off
  application:
    name: fractional-calculus-computation-api

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.trbaxter.github.fractionalcomputationapi: ${LOGGING_LEVEL_CUSTOM:DEBUG}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}