name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22.0.1
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22.0.1'

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}